/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JubileeRouteImport } from './routes/jubilee'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FacultyFacultySlugRouteImport } from './routes/faculty.$facultySlug'
import { Route as DepartmentsDepartmentIdRouteImport } from './routes/departments.$departmentId'
import { Route as CollegesCollegeIdRouteImport } from './routes/colleges.$collegeId'

const JubileeRoute = JubileeRouteImport.update({
  id: '/jubilee',
  path: '/jubilee',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyFacultySlugRoute = FacultyFacultySlugRouteImport.update({
  id: '/$facultySlug',
  path: '/$facultySlug',
  getParentRoute: () => FacultyRoute,
} as any)
const DepartmentsDepartmentIdRoute = DepartmentsDepartmentIdRouteImport.update({
  id: '/departments/$departmentId',
  path: '/departments/$departmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegesCollegeIdRoute = CollegesCollegeIdRouteImport.update({
  id: '/colleges/$collegeId',
  path: '/colleges/$collegeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faculty': typeof FacultyRouteWithChildren
  '/jubilee': typeof JubileeRoute
  '/colleges/$collegeId': typeof CollegesCollegeIdRoute
  '/departments/$departmentId': typeof DepartmentsDepartmentIdRoute
  '/faculty/$facultySlug': typeof FacultyFacultySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faculty': typeof FacultyRouteWithChildren
  '/jubilee': typeof JubileeRoute
  '/colleges/$collegeId': typeof CollegesCollegeIdRoute
  '/departments/$departmentId': typeof DepartmentsDepartmentIdRoute
  '/faculty/$facultySlug': typeof FacultyFacultySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faculty': typeof FacultyRouteWithChildren
  '/jubilee': typeof JubileeRoute
  '/colleges/$collegeId': typeof CollegesCollegeIdRoute
  '/departments/$departmentId': typeof DepartmentsDepartmentIdRoute
  '/faculty/$facultySlug': typeof FacultyFacultySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faculty'
    | '/jubilee'
    | '/colleges/$collegeId'
    | '/departments/$departmentId'
    | '/faculty/$facultySlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faculty'
    | '/jubilee'
    | '/colleges/$collegeId'
    | '/departments/$departmentId'
    | '/faculty/$facultySlug'
  id:
    | '__root__'
    | '/'
    | '/faculty'
    | '/jubilee'
    | '/colleges/$collegeId'
    | '/departments/$departmentId'
    | '/faculty/$facultySlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FacultyRoute: typeof FacultyRouteWithChildren
  JubileeRoute: typeof JubileeRoute
  CollegesCollegeIdRoute: typeof CollegesCollegeIdRoute
  DepartmentsDepartmentIdRoute: typeof DepartmentsDepartmentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/jubilee': {
      id: '/jubilee'
      path: '/jubilee'
      fullPath: '/jubilee'
      preLoaderRoute: typeof JubileeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/$facultySlug': {
      id: '/faculty/$facultySlug'
      path: '/$facultySlug'
      fullPath: '/faculty/$facultySlug'
      preLoaderRoute: typeof FacultyFacultySlugRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/departments/$departmentId': {
      id: '/departments/$departmentId'
      path: '/departments/$departmentId'
      fullPath: '/departments/$departmentId'
      preLoaderRoute: typeof DepartmentsDepartmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colleges/$collegeId': {
      id: '/colleges/$collegeId'
      path: '/colleges/$collegeId'
      fullPath: '/colleges/$collegeId'
      preLoaderRoute: typeof CollegesCollegeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FacultyRouteChildren {
  FacultyFacultySlugRoute: typeof FacultyFacultySlugRoute
}

const FacultyRouteChildren: FacultyRouteChildren = {
  FacultyFacultySlugRoute: FacultyFacultySlugRoute,
}

const FacultyRouteWithChildren =
  FacultyRoute._addFileChildren(FacultyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FacultyRoute: FacultyRouteWithChildren,
  JubileeRoute: JubileeRoute,
  CollegesCollegeIdRoute: CollegesCollegeIdRoute,
  DepartmentsDepartmentIdRoute: DepartmentsDepartmentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
