/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JubileeRouteImport } from './routes/jubilee'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as AboutprofileRouteImport } from './routes/aboutprofile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentServicesIndexRouteImport } from './routes/student-services.index'
import { Route as EmployeeServicesIndexRouteImport } from './routes/employee-services.index'
import { Route as StudentServicesPageIdRouteImport } from './routes/student-services.$pageId'
import { Route as PagesSectionRouteImport } from './routes/pages.$section'
import { Route as FacultyFacultySlugRouteImport } from './routes/faculty.$facultySlug'
import { Route as EmployeeServicesPageIdRouteImport } from './routes/employee-services.$pageId'
import { Route as DepartmentsDepartmentIdRouteImport } from './routes/departments.$departmentId'
import { Route as CollegesCollegeIdRouteImport } from './routes/colleges.$collegeId'
import { Route as AdmissionsPageIdRouteImport } from './routes/admissions.$pageId'

const JubileeRoute = JubileeRouteImport.update({
  id: '/jubilee',
  path: '/jubilee',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutprofileRoute = AboutprofileRouteImport.update({
  id: '/aboutprofile',
  path: '/aboutprofile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentServicesIndexRoute = StudentServicesIndexRouteImport.update({
  id: '/student-services/',
  path: '/student-services/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeServicesIndexRoute = EmployeeServicesIndexRouteImport.update({
  id: '/employee-services/',
  path: '/employee-services/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentServicesPageIdRoute = StudentServicesPageIdRouteImport.update({
  id: '/student-services/$pageId',
  path: '/student-services/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSectionRoute = PagesSectionRouteImport.update({
  id: '/pages/$section',
  path: '/pages/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyFacultySlugRoute = FacultyFacultySlugRouteImport.update({
  id: '/$facultySlug',
  path: '/$facultySlug',
  getParentRoute: () => FacultyRoute,
} as any)
const EmployeeServicesPageIdRoute = EmployeeServicesPageIdRouteImport.update({
  id: '/employee-services/$pageId',
  path: '/employee-services/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsDepartmentIdRoute = DepartmentsDepartmentIdRouteImport.update({
  id: '/departments/$departmentId',
  path: '/departments/$departmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegesCollegeIdRoute = CollegesCollegeIdRouteImport.update({
  id: '/colleges/$collegeId',
  path: '/colleges/$collegeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsPageIdRoute = AdmissionsPageIdRouteImport.update({
  id: '/admissions/$pageId',
  path: '/admissions/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aboutprofile': typeof AboutprofileRoute
  '/faculty': typeof FacultyRouteWithChildren
  '/history': typeof HistoryRoute
  '/jubilee': typeof JubileeRoute
  '/admissions/$pageId': typeof AdmissionsPageIdRoute
  '/colleges/$collegeId': typeof CollegesCollegeIdRoute
  '/departments/$departmentId': typeof DepartmentsDepartmentIdRoute
  '/employee-services/$pageId': typeof EmployeeServicesPageIdRoute
  '/faculty/$facultySlug': typeof FacultyFacultySlugRoute
  '/pages/$section': typeof PagesSectionRoute
  '/student-services/$pageId': typeof StudentServicesPageIdRoute
  '/employee-services/': typeof EmployeeServicesIndexRoute
  '/student-services/': typeof StudentServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aboutprofile': typeof AboutprofileRoute
  '/faculty': typeof FacultyRouteWithChildren
  '/history': typeof HistoryRoute
  '/jubilee': typeof JubileeRoute
  '/admissions/$pageId': typeof AdmissionsPageIdRoute
  '/colleges/$collegeId': typeof CollegesCollegeIdRoute
  '/departments/$departmentId': typeof DepartmentsDepartmentIdRoute
  '/employee-services/$pageId': typeof EmployeeServicesPageIdRoute
  '/faculty/$facultySlug': typeof FacultyFacultySlugRoute
  '/pages/$section': typeof PagesSectionRoute
  '/student-services/$pageId': typeof StudentServicesPageIdRoute
  '/employee-services': typeof EmployeeServicesIndexRoute
  '/student-services': typeof StudentServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aboutprofile': typeof AboutprofileRoute
  '/faculty': typeof FacultyRouteWithChildren
  '/history': typeof HistoryRoute
  '/jubilee': typeof JubileeRoute
  '/admissions/$pageId': typeof AdmissionsPageIdRoute
  '/colleges/$collegeId': typeof CollegesCollegeIdRoute
  '/departments/$departmentId': typeof DepartmentsDepartmentIdRoute
  '/employee-services/$pageId': typeof EmployeeServicesPageIdRoute
  '/faculty/$facultySlug': typeof FacultyFacultySlugRoute
  '/pages/$section': typeof PagesSectionRoute
  '/student-services/$pageId': typeof StudentServicesPageIdRoute
  '/employee-services/': typeof EmployeeServicesIndexRoute
  '/student-services/': typeof StudentServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aboutprofile'
    | '/faculty'
    | '/history'
    | '/jubilee'
    | '/admissions/$pageId'
    | '/colleges/$collegeId'
    | '/departments/$departmentId'
    | '/employee-services/$pageId'
    | '/faculty/$facultySlug'
    | '/pages/$section'
    | '/student-services/$pageId'
    | '/employee-services/'
    | '/student-services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aboutprofile'
    | '/faculty'
    | '/history'
    | '/jubilee'
    | '/admissions/$pageId'
    | '/colleges/$collegeId'
    | '/departments/$departmentId'
    | '/employee-services/$pageId'
    | '/faculty/$facultySlug'
    | '/pages/$section'
    | '/student-services/$pageId'
    | '/employee-services'
    | '/student-services'
  id:
    | '__root__'
    | '/'
    | '/aboutprofile'
    | '/faculty'
    | '/history'
    | '/jubilee'
    | '/admissions/$pageId'
    | '/colleges/$collegeId'
    | '/departments/$departmentId'
    | '/employee-services/$pageId'
    | '/faculty/$facultySlug'
    | '/pages/$section'
    | '/student-services/$pageId'
    | '/employee-services/'
    | '/student-services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutprofileRoute: typeof AboutprofileRoute
  FacultyRoute: typeof FacultyRouteWithChildren
  HistoryRoute: typeof HistoryRoute
  JubileeRoute: typeof JubileeRoute
  AdmissionsPageIdRoute: typeof AdmissionsPageIdRoute
  CollegesCollegeIdRoute: typeof CollegesCollegeIdRoute
  DepartmentsDepartmentIdRoute: typeof DepartmentsDepartmentIdRoute
  EmployeeServicesPageIdRoute: typeof EmployeeServicesPageIdRoute
  PagesSectionRoute: typeof PagesSectionRoute
  StudentServicesPageIdRoute: typeof StudentServicesPageIdRoute
  EmployeeServicesIndexRoute: typeof EmployeeServicesIndexRoute
  StudentServicesIndexRoute: typeof StudentServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/jubilee': {
      id: '/jubilee'
      path: '/jubilee'
      fullPath: '/jubilee'
      preLoaderRoute: typeof JubileeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aboutprofile': {
      id: '/aboutprofile'
      path: '/aboutprofile'
      fullPath: '/aboutprofile'
      preLoaderRoute: typeof AboutprofileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-services/': {
      id: '/student-services/'
      path: '/student-services'
      fullPath: '/student-services/'
      preLoaderRoute: typeof StudentServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee-services/': {
      id: '/employee-services/'
      path: '/employee-services'
      fullPath: '/employee-services/'
      preLoaderRoute: typeof EmployeeServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-services/$pageId': {
      id: '/student-services/$pageId'
      path: '/student-services/$pageId'
      fullPath: '/student-services/$pageId'
      preLoaderRoute: typeof StudentServicesPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$section': {
      id: '/pages/$section'
      path: '/pages/$section'
      fullPath: '/pages/$section'
      preLoaderRoute: typeof PagesSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/$facultySlug': {
      id: '/faculty/$facultySlug'
      path: '/$facultySlug'
      fullPath: '/faculty/$facultySlug'
      preLoaderRoute: typeof FacultyFacultySlugRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/employee-services/$pageId': {
      id: '/employee-services/$pageId'
      path: '/employee-services/$pageId'
      fullPath: '/employee-services/$pageId'
      preLoaderRoute: typeof EmployeeServicesPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/$departmentId': {
      id: '/departments/$departmentId'
      path: '/departments/$departmentId'
      fullPath: '/departments/$departmentId'
      preLoaderRoute: typeof DepartmentsDepartmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colleges/$collegeId': {
      id: '/colleges/$collegeId'
      path: '/colleges/$collegeId'
      fullPath: '/colleges/$collegeId'
      preLoaderRoute: typeof CollegesCollegeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/$pageId': {
      id: '/admissions/$pageId'
      path: '/admissions/$pageId'
      fullPath: '/admissions/$pageId'
      preLoaderRoute: typeof AdmissionsPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FacultyRouteChildren {
  FacultyFacultySlugRoute: typeof FacultyFacultySlugRoute
}

const FacultyRouteChildren: FacultyRouteChildren = {
  FacultyFacultySlugRoute: FacultyFacultySlugRoute,
}

const FacultyRouteWithChildren =
  FacultyRoute._addFileChildren(FacultyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutprofileRoute: AboutprofileRoute,
  FacultyRoute: FacultyRouteWithChildren,
  HistoryRoute: HistoryRoute,
  JubileeRoute: JubileeRoute,
  AdmissionsPageIdRoute: AdmissionsPageIdRoute,
  CollegesCollegeIdRoute: CollegesCollegeIdRoute,
  DepartmentsDepartmentIdRoute: DepartmentsDepartmentIdRoute,
  EmployeeServicesPageIdRoute: EmployeeServicesPageIdRoute,
  PagesSectionRoute: PagesSectionRoute,
  StudentServicesPageIdRoute: StudentServicesPageIdRoute,
  EmployeeServicesIndexRoute: EmployeeServicesIndexRoute,
  StudentServicesIndexRoute: StudentServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
