/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JubileeRouteImport } from './routes/jubilee'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as AboutprofileRouteImport } from './routes/aboutprofile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentServicesIndexRouteImport } from './routes/student-services.index'
import { Route as ResearchIndexRouteImport } from './routes/research.index'
import { Route as RankingsIndexRouteImport } from './routes/rankings.index'
import { Route as ProgramsIndexRouteImport } from './routes/programs.index'
import { Route as EmployeeServicesIndexRouteImport } from './routes/employee-services.index'
import { Route as CampusLifeIndexRouteImport } from './routes/campus-life.index'
import { Route as StudentServicesPageIdRouteImport } from './routes/student-services.$pageId'
import { Route as ResearchPageIdRouteImport } from './routes/research.$pageId'
import { Route as RankingsPageIdRouteImport } from './routes/rankings.$pageId'
import { Route as ProgramsPageIdRouteImport } from './routes/programs.$pageId'
import { Route as PagesSectionRouteImport } from './routes/pages.$section'
import { Route as FacultyFacultySlugRouteImport } from './routes/faculty.$facultySlug'
import { Route as EmployeeServicesPageIdRouteImport } from './routes/employee-services.$pageId'
import { Route as DepartmentsDepartmentIdRouteImport } from './routes/departments.$departmentId'
import { Route as CollegesCollegeIdRouteImport } from './routes/colleges.$collegeId'
import { Route as CampusLifePageIdRouteImport } from './routes/campus-life.$pageId'
import { Route as AdmissionsPageIdRouteImport } from './routes/admissions.$pageId'
import { Route as AcademicsPageIdRouteImport } from './routes/academics.$pageId'
import { Route as AboutPageIdRouteImport } from './routes/about.$pageId'

const JubileeRoute = JubileeRouteImport.update({
  id: '/jubilee',
  path: '/jubilee',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutprofileRoute = AboutprofileRouteImport.update({
  id: '/aboutprofile',
  path: '/aboutprofile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentServicesIndexRoute = StudentServicesIndexRouteImport.update({
  id: '/student-services/',
  path: '/student-services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchIndexRoute = ResearchIndexRouteImport.update({
  id: '/research/',
  path: '/research/',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsIndexRoute = RankingsIndexRouteImport.update({
  id: '/rankings/',
  path: '/rankings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeServicesIndexRoute = EmployeeServicesIndexRouteImport.update({
  id: '/employee-services/',
  path: '/employee-services/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusLifeIndexRoute = CampusLifeIndexRouteImport.update({
  id: '/campus-life/',
  path: '/campus-life/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentServicesPageIdRoute = StudentServicesPageIdRouteImport.update({
  id: '/student-services/$pageId',
  path: '/student-services/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchPageIdRoute = ResearchPageIdRouteImport.update({
  id: '/research/$pageId',
  path: '/research/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsPageIdRoute = RankingsPageIdRouteImport.update({
  id: '/rankings/$pageId',
  path: '/rankings/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsPageIdRoute = ProgramsPageIdRouteImport.update({
  id: '/programs/$pageId',
  path: '/programs/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSectionRoute = PagesSectionRouteImport.update({
  id: '/pages/$section',
  path: '/pages/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyFacultySlugRoute = FacultyFacultySlugRouteImport.update({
  id: '/$facultySlug',
  path: '/$facultySlug',
  getParentRoute: () => FacultyRoute,
} as any)
const EmployeeServicesPageIdRoute = EmployeeServicesPageIdRouteImport.update({
  id: '/employee-services/$pageId',
  path: '/employee-services/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsDepartmentIdRoute = DepartmentsDepartmentIdRouteImport.update({
  id: '/departments/$departmentId',
  path: '/departments/$departmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegesCollegeIdRoute = CollegesCollegeIdRouteImport.update({
  id: '/colleges/$collegeId',
  path: '/colleges/$collegeId',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusLifePageIdRoute = CampusLifePageIdRouteImport.update({
  id: '/campus-life/$pageId',
  path: '/campus-life/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsPageIdRoute = AdmissionsPageIdRouteImport.update({
  id: '/admissions/$pageId',
  path: '/admissions/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsPageIdRoute = AcademicsPageIdRouteImport.update({
  id: '/academics/$pageId',
  path: '/academics/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutPageIdRoute = AboutPageIdRouteImport.update({
  id: '/about/$pageId',
  path: '/about/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aboutprofile': typeof AboutprofileRoute
  '/faculty': typeof FacultyRouteWithChildren
  '/history': typeof HistoryRoute
  '/jubilee': typeof JubileeRoute
  '/about/$pageId': typeof AboutPageIdRoute
  '/academics/$pageId': typeof AcademicsPageIdRoute
  '/admissions/$pageId': typeof AdmissionsPageIdRoute
  '/campus-life/$pageId': typeof CampusLifePageIdRoute
  '/colleges/$collegeId': typeof CollegesCollegeIdRoute
  '/departments/$departmentId': typeof DepartmentsDepartmentIdRoute
  '/employee-services/$pageId': typeof EmployeeServicesPageIdRoute
  '/faculty/$facultySlug': typeof FacultyFacultySlugRoute
  '/pages/$section': typeof PagesSectionRoute
  '/programs/$pageId': typeof ProgramsPageIdRoute
  '/rankings/$pageId': typeof RankingsPageIdRoute
  '/research/$pageId': typeof ResearchPageIdRoute
  '/student-services/$pageId': typeof StudentServicesPageIdRoute
  '/campus-life/': typeof CampusLifeIndexRoute
  '/employee-services/': typeof EmployeeServicesIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/rankings/': typeof RankingsIndexRoute
  '/research/': typeof ResearchIndexRoute
  '/student-services/': typeof StudentServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aboutprofile': typeof AboutprofileRoute
  '/faculty': typeof FacultyRouteWithChildren
  '/history': typeof HistoryRoute
  '/jubilee': typeof JubileeRoute
  '/about/$pageId': typeof AboutPageIdRoute
  '/academics/$pageId': typeof AcademicsPageIdRoute
  '/admissions/$pageId': typeof AdmissionsPageIdRoute
  '/campus-life/$pageId': typeof CampusLifePageIdRoute
  '/colleges/$collegeId': typeof CollegesCollegeIdRoute
  '/departments/$departmentId': typeof DepartmentsDepartmentIdRoute
  '/employee-services/$pageId': typeof EmployeeServicesPageIdRoute
  '/faculty/$facultySlug': typeof FacultyFacultySlugRoute
  '/pages/$section': typeof PagesSectionRoute
  '/programs/$pageId': typeof ProgramsPageIdRoute
  '/rankings/$pageId': typeof RankingsPageIdRoute
  '/research/$pageId': typeof ResearchPageIdRoute
  '/student-services/$pageId': typeof StudentServicesPageIdRoute
  '/campus-life': typeof CampusLifeIndexRoute
  '/employee-services': typeof EmployeeServicesIndexRoute
  '/programs': typeof ProgramsIndexRoute
  '/rankings': typeof RankingsIndexRoute
  '/research': typeof ResearchIndexRoute
  '/student-services': typeof StudentServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aboutprofile': typeof AboutprofileRoute
  '/faculty': typeof FacultyRouteWithChildren
  '/history': typeof HistoryRoute
  '/jubilee': typeof JubileeRoute
  '/about/$pageId': typeof AboutPageIdRoute
  '/academics/$pageId': typeof AcademicsPageIdRoute
  '/admissions/$pageId': typeof AdmissionsPageIdRoute
  '/campus-life/$pageId': typeof CampusLifePageIdRoute
  '/colleges/$collegeId': typeof CollegesCollegeIdRoute
  '/departments/$departmentId': typeof DepartmentsDepartmentIdRoute
  '/employee-services/$pageId': typeof EmployeeServicesPageIdRoute
  '/faculty/$facultySlug': typeof FacultyFacultySlugRoute
  '/pages/$section': typeof PagesSectionRoute
  '/programs/$pageId': typeof ProgramsPageIdRoute
  '/rankings/$pageId': typeof RankingsPageIdRoute
  '/research/$pageId': typeof ResearchPageIdRoute
  '/student-services/$pageId': typeof StudentServicesPageIdRoute
  '/campus-life/': typeof CampusLifeIndexRoute
  '/employee-services/': typeof EmployeeServicesIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/rankings/': typeof RankingsIndexRoute
  '/research/': typeof ResearchIndexRoute
  '/student-services/': typeof StudentServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aboutprofile'
    | '/faculty'
    | '/history'
    | '/jubilee'
    | '/about/$pageId'
    | '/academics/$pageId'
    | '/admissions/$pageId'
    | '/campus-life/$pageId'
    | '/colleges/$collegeId'
    | '/departments/$departmentId'
    | '/employee-services/$pageId'
    | '/faculty/$facultySlug'
    | '/pages/$section'
    | '/programs/$pageId'
    | '/rankings/$pageId'
    | '/research/$pageId'
    | '/student-services/$pageId'
    | '/campus-life/'
    | '/employee-services/'
    | '/programs/'
    | '/rankings/'
    | '/research/'
    | '/student-services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aboutprofile'
    | '/faculty'
    | '/history'
    | '/jubilee'
    | '/about/$pageId'
    | '/academics/$pageId'
    | '/admissions/$pageId'
    | '/campus-life/$pageId'
    | '/colleges/$collegeId'
    | '/departments/$departmentId'
    | '/employee-services/$pageId'
    | '/faculty/$facultySlug'
    | '/pages/$section'
    | '/programs/$pageId'
    | '/rankings/$pageId'
    | '/research/$pageId'
    | '/student-services/$pageId'
    | '/campus-life'
    | '/employee-services'
    | '/programs'
    | '/rankings'
    | '/research'
    | '/student-services'
  id:
    | '__root__'
    | '/'
    | '/aboutprofile'
    | '/faculty'
    | '/history'
    | '/jubilee'
    | '/about/$pageId'
    | '/academics/$pageId'
    | '/admissions/$pageId'
    | '/campus-life/$pageId'
    | '/colleges/$collegeId'
    | '/departments/$departmentId'
    | '/employee-services/$pageId'
    | '/faculty/$facultySlug'
    | '/pages/$section'
    | '/programs/$pageId'
    | '/rankings/$pageId'
    | '/research/$pageId'
    | '/student-services/$pageId'
    | '/campus-life/'
    | '/employee-services/'
    | '/programs/'
    | '/rankings/'
    | '/research/'
    | '/student-services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutprofileRoute: typeof AboutprofileRoute
  FacultyRoute: typeof FacultyRouteWithChildren
  HistoryRoute: typeof HistoryRoute
  JubileeRoute: typeof JubileeRoute
  AboutPageIdRoute: typeof AboutPageIdRoute
  AcademicsPageIdRoute: typeof AcademicsPageIdRoute
  AdmissionsPageIdRoute: typeof AdmissionsPageIdRoute
  CampusLifePageIdRoute: typeof CampusLifePageIdRoute
  CollegesCollegeIdRoute: typeof CollegesCollegeIdRoute
  DepartmentsDepartmentIdRoute: typeof DepartmentsDepartmentIdRoute
  EmployeeServicesPageIdRoute: typeof EmployeeServicesPageIdRoute
  PagesSectionRoute: typeof PagesSectionRoute
  ProgramsPageIdRoute: typeof ProgramsPageIdRoute
  RankingsPageIdRoute: typeof RankingsPageIdRoute
  ResearchPageIdRoute: typeof ResearchPageIdRoute
  StudentServicesPageIdRoute: typeof StudentServicesPageIdRoute
  CampusLifeIndexRoute: typeof CampusLifeIndexRoute
  EmployeeServicesIndexRoute: typeof EmployeeServicesIndexRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
  RankingsIndexRoute: typeof RankingsIndexRoute
  ResearchIndexRoute: typeof ResearchIndexRoute
  StudentServicesIndexRoute: typeof StudentServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/jubilee': {
      id: '/jubilee'
      path: '/jubilee'
      fullPath: '/jubilee'
      preLoaderRoute: typeof JubileeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aboutprofile': {
      id: '/aboutprofile'
      path: '/aboutprofile'
      fullPath: '/aboutprofile'
      preLoaderRoute: typeof AboutprofileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-services/': {
      id: '/student-services/'
      path: '/student-services'
      fullPath: '/student-services/'
      preLoaderRoute: typeof StudentServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/': {
      id: '/research/'
      path: '/research'
      fullPath: '/research/'
      preLoaderRoute: typeof ResearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/': {
      id: '/rankings/'
      path: '/rankings'
      fullPath: '/rankings/'
      preLoaderRoute: typeof RankingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee-services/': {
      id: '/employee-services/'
      path: '/employee-services'
      fullPath: '/employee-services/'
      preLoaderRoute: typeof EmployeeServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus-life/': {
      id: '/campus-life/'
      path: '/campus-life'
      fullPath: '/campus-life/'
      preLoaderRoute: typeof CampusLifeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-services/$pageId': {
      id: '/student-services/$pageId'
      path: '/student-services/$pageId'
      fullPath: '/student-services/$pageId'
      preLoaderRoute: typeof StudentServicesPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/$pageId': {
      id: '/research/$pageId'
      path: '/research/$pageId'
      fullPath: '/research/$pageId'
      preLoaderRoute: typeof ResearchPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/$pageId': {
      id: '/rankings/$pageId'
      path: '/rankings/$pageId'
      fullPath: '/rankings/$pageId'
      preLoaderRoute: typeof RankingsPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$pageId': {
      id: '/programs/$pageId'
      path: '/programs/$pageId'
      fullPath: '/programs/$pageId'
      preLoaderRoute: typeof ProgramsPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$section': {
      id: '/pages/$section'
      path: '/pages/$section'
      fullPath: '/pages/$section'
      preLoaderRoute: typeof PagesSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/$facultySlug': {
      id: '/faculty/$facultySlug'
      path: '/$facultySlug'
      fullPath: '/faculty/$facultySlug'
      preLoaderRoute: typeof FacultyFacultySlugRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/employee-services/$pageId': {
      id: '/employee-services/$pageId'
      path: '/employee-services/$pageId'
      fullPath: '/employee-services/$pageId'
      preLoaderRoute: typeof EmployeeServicesPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/$departmentId': {
      id: '/departments/$departmentId'
      path: '/departments/$departmentId'
      fullPath: '/departments/$departmentId'
      preLoaderRoute: typeof DepartmentsDepartmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colleges/$collegeId': {
      id: '/colleges/$collegeId'
      path: '/colleges/$collegeId'
      fullPath: '/colleges/$collegeId'
      preLoaderRoute: typeof CollegesCollegeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus-life/$pageId': {
      id: '/campus-life/$pageId'
      path: '/campus-life/$pageId'
      fullPath: '/campus-life/$pageId'
      preLoaderRoute: typeof CampusLifePageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/$pageId': {
      id: '/admissions/$pageId'
      path: '/admissions/$pageId'
      fullPath: '/admissions/$pageId'
      preLoaderRoute: typeof AdmissionsPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/$pageId': {
      id: '/academics/$pageId'
      path: '/academics/$pageId'
      fullPath: '/academics/$pageId'
      preLoaderRoute: typeof AcademicsPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/$pageId': {
      id: '/about/$pageId'
      path: '/about/$pageId'
      fullPath: '/about/$pageId'
      preLoaderRoute: typeof AboutPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FacultyRouteChildren {
  FacultyFacultySlugRoute: typeof FacultyFacultySlugRoute
}

const FacultyRouteChildren: FacultyRouteChildren = {
  FacultyFacultySlugRoute: FacultyFacultySlugRoute,
}

const FacultyRouteWithChildren =
  FacultyRoute._addFileChildren(FacultyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutprofileRoute: AboutprofileRoute,
  FacultyRoute: FacultyRouteWithChildren,
  HistoryRoute: HistoryRoute,
  JubileeRoute: JubileeRoute,
  AboutPageIdRoute: AboutPageIdRoute,
  AcademicsPageIdRoute: AcademicsPageIdRoute,
  AdmissionsPageIdRoute: AdmissionsPageIdRoute,
  CampusLifePageIdRoute: CampusLifePageIdRoute,
  CollegesCollegeIdRoute: CollegesCollegeIdRoute,
  DepartmentsDepartmentIdRoute: DepartmentsDepartmentIdRoute,
  EmployeeServicesPageIdRoute: EmployeeServicesPageIdRoute,
  PagesSectionRoute: PagesSectionRoute,
  ProgramsPageIdRoute: ProgramsPageIdRoute,
  RankingsPageIdRoute: RankingsPageIdRoute,
  ResearchPageIdRoute: ResearchPageIdRoute,
  StudentServicesPageIdRoute: StudentServicesPageIdRoute,
  CampusLifeIndexRoute: CampusLifeIndexRoute,
  EmployeeServicesIndexRoute: EmployeeServicesIndexRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
  RankingsIndexRoute: RankingsIndexRoute,
  ResearchIndexRoute: ResearchIndexRoute,
  StudentServicesIndexRoute: StudentServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
